//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using Chloe.Annotations;
using System.ComponentModel.DataAnnotations;

namespace WaterCloud.Domain.SystemSecurity
{
    /// <summary>
	/// 定时任务
	/// </summary>
    [Table("sys_openjoblog")]
    public partial class OpenJobLogEntity : IEntity<OpenJobEntity>
    {
        [ColumnAttribute("F_Id", IsPrimaryKey = true)]
        public string F_Id { get; set; }
        /// <summary>
        /// 任务名称
        /// </summary>
        [Description("任务名称")]
        public string F_JobName { get; set; }
        /// <summary>
        /// 任务组别
        /// </summary>
        [Description("任务Id")]
        public string F_JobId { get; set; }
        /// <summary>
        /// 文件名称
        /// </summary>
        [Description("任务信息")]
        public string F_Description { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        [Description("执行时间")]
        public System.DateTime? F_CreatorTime { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        [Description("执行状态")]
        public bool? F_EnabledMark { get; set; }
    }
}