//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using SqlSugar;

namespace WaterCloud.Domain.FlowManage
{
    /// <summary>
	/// 工作流实例流转历史记录
	/// </summary>
      [SugarTable("oms_flowinstancehis")]
    public class FlowInstanceTransitionHistory
    {
        /// <summary>
        /// 主键Id
        /// </summary>
        /// <returns></returns>
        [SugarColumn(ColumnName ="Id", IsPrimaryKey = true, ColumnDescription = "主键Id")]
        public string Id { get; set; }
        /// <summary>
        /// 实例Id
        /// </summary>
        [SugarColumn(IsNullable = false, ColumnName = "InstanceId", ColumnDataType = "nvarchar(50)", ColumnDescription = "实例Id")]
        public string InstanceId { get; set; }
        /// <summary>
	    /// 开始节点Id
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "FromNodeId",ColumnDataType = "nvarchar(50)", ColumnDescription = "开始节点Id")]
        public string FromNodeId { get; set; }
        /// <summary>
	    /// 开始节点类型
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnDescription = "开始节点类型")]
        public int? FromNodeType { get; set; }
        /// <summary>
	    /// 开始节点名称
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "FromNodeName", ColumnDataType = "nvarchar(200)", ColumnDescription = "开始节点名称")]
        public string FromNodeName { get; set; }
        /// <summary>
	    /// 结束节点Id
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "ToNodeId",ColumnDataType = "nvarchar(50)", ColumnDescription = "结束节点Id")]
        public string ToNodeId { get; set; }
        /// <summary>
	    /// 结束节点类型
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnDescription = "结束节点类型")]
        public int? ToNodeType { get; set; }
        /// <summary>
	    /// 结束节点名称
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "ToNodeName", ColumnDataType = "nvarchar(200)", ColumnDescription = "结束节点名称")]
        public string ToNodeName { get; set; }
        /// <summary>
	    /// 转化状态
	    /// </summary>
        [SugarColumn(IsNullable = false, ColumnDescription = "转化状态")]
        public bool TransitionSate { get; set; }
        /// <summary>
	    /// 是否结束
	    /// </summary>
        [SugarColumn(IsNullable = false,ColumnDescription = "是否结束")]
        public bool IsFinish { get; set; }
        /// <summary>
	    /// 转化时间
	    /// </summary>
        [SugarColumn(IsNullable = false, ColumnDescription = "转化时间")]
        public DateTime CreatorTime { get; set; }
        /// <summary>
        /// 创建用户主键
        /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "CreatorUserId", ColumnDataType = "nvarchar(50)", ColumnDescription = "创建用户主键")]
        public string CreatorUserId { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "CreatorUserName", ColumnDataType = "nvarchar(50)", ColumnDescription = "创建用户")]
        public string CreatorUserName { get; set; }

    }
}