//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using SqlSugar;

namespace WaterCloud.Domain.FlowManage
{
    /// <summary>
	/// 工作流实例流转历史记录
	/// </summary>
      [SugarTable("oms_flowinstancehis")]
    public class FlowInstanceTransitionHistory
    {
        /// <summary>
        /// 主键Id
        /// </summary>
        /// <returns></returns>
        [SugarColumn(ColumnName ="F_Id", IsPrimaryKey = true, ColumnDescription = "主键Id")]
        public string F_Id { get; set; }
        /// <summary>
        /// 实例Id
        /// </summary>
        [SugarColumn(IsNullable = false, ColumnName = "F_InstanceId", ColumnDataType = "nvarchar(50)", ColumnDescription = "实例Id")]
        public string F_InstanceId { get; set; }
        /// <summary>
	    /// 开始节点Id
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "F_FromNodeId",ColumnDataType = "nvarchar(50)", ColumnDescription = "开始节点Id")]
        public string F_FromNodeId { get; set; }
        /// <summary>
	    /// 开始节点类型
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnDescription = "开始节点类型")]
        public int? F_FromNodeType { get; set; }
        /// <summary>
	    /// 开始节点名称
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "F_FromNodeName", ColumnDataType = "nvarchar(200)", ColumnDescription = "开始节点名称")]
        public string F_FromNodeName { get; set; }
        /// <summary>
	    /// 结束节点Id
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "F_ToNodeId",ColumnDataType = "nvarchar(50)", ColumnDescription = "结束节点Id")]
        public string F_ToNodeId { get; set; }
        /// <summary>
	    /// 结束节点类型
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnDescription = "结束节点类型")]
        public int? F_ToNodeType { get; set; }
        /// <summary>
	    /// 结束节点名称
	    /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "F_ToNodeName", ColumnDataType = "nvarchar(200)", ColumnDescription = "结束节点名称")]
        public string F_ToNodeName { get; set; }
        /// <summary>
	    /// 转化状态
	    /// </summary>
        [SugarColumn(IsNullable = false, ColumnDescription = "转化状态")]
        public bool F_TransitionSate { get; set; }
        /// <summary>
	    /// 是否结束
	    /// </summary>
        [SugarColumn(IsNullable = false,ColumnDescription = "是否结束")]
        public bool F_IsFinish { get; set; }
        /// <summary>
	    /// 转化时间
	    /// </summary>
        [SugarColumn(IsNullable = false, ColumnDescription = "转化时间")]
        public DateTime F_CreatorTime { get; set; }
        /// <summary>
        /// 创建用户主键
        /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "F_CreatorUserId", ColumnDataType = "nvarchar(50)", ColumnDescription = "创建用户主键")]
        public string F_CreatorUserId { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        [SugarColumn(IsNullable = true, ColumnName = "F_CreatorUserName", ColumnDataType = "nvarchar(50)", ColumnDescription = "创建用户")]
        public string F_CreatorUserName { get; set; }

    }
}